### PR TITLE
Made changes to README and Scraper

### PR DESCRIPTION
**Pull request by HemanthTenneti**
# Changes
## README.md
- Fixed inconsistencies in text formatting.
- Updated the terminal commands to be more readable and relevant to people who are inexperienced in Git.
- Renamed from Readme.md as complete uppercase for README files is generally preferred amongst the coding community.

## Scraper.py
- Added inputs for website and element name, as it allows for more functionality as a web-scraper instead of being locked in to a default website.

### CODE REVIEW

**Comment by sunny7899** [comment]
@HemanthTenneti  Can you please keep the sample website and class name for testing

**Comment by HemanthTenneti** [comment]
Thank you for getting back to me, and definitely!

**Comment by HemanthTenneti** [comment]
Created an issue at your advise.
Issue #9

**Comment by sunny7899** [comment]
@HemanthTenneti  i am not asking to remove input handling keep the data as notes/commnet that test data.

**Comment by HemanthTenneti** [comment]
Got it! Will add that.

**Comment by HemanthTenneti** [comment]
Please let me know of any more changes.

**Pull request merged**
